# Generated by Django 3.2.12 on 2023-11-30 02:45

import django.core.validators
from django.db import migrations, models
import pokemon_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0002_auto_20231130_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='Unknown', validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(150)]),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[pokemon_app.validators.validate_name]),
        ),
    ]
