# Generated by Django 4.2.4 on 2023-12-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crypto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "circulating_supply",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("image_url", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=255)),
            ],
        ),
    ]
