# Generated by Django 3.2.12 on 2023-12-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('daily_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('day_high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('day_low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('circulating_supply', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('max_supply', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
