# Generated by Django 3.2.12 on 2023-12-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='circulating_supply',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='day_high_price',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='day_low_price',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='max_supply',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='open_price',
        ),
    ]
