# Generated by Django 4.2.4 on 2023-12-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0008_alter_crypto_circulating_supply_alter_crypto_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='name',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='symbol',
        ),
    ]
