# Generated by Django 4.2.4 on 2023-12-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0009_remove_crypto_image_url_remove_crypto_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='crypto',
            name='symbol',
            field=models.CharField(default='', max_length=255),
        ),
    ]
