# Generated by Django 4.2.4 on 2023-12-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0010_crypto_name_crypto_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='circulating_supply',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
